"""RaaS Core - Shared requirements management engine."""

__version__ = "1.0.0"

from .models import (
    Base,
    User,
    Organization,
    OrganizationMember,
    Project,
    ProjectMember,
    Requirement,
    RequirementHistory,
    PersonalAccessToken,
    RequirementType,
    LifecycleStatus,
    ProjectStatus,
    ProjectVisibility,
    ProjectRole,
    MemberRole,
)
from .crud import (
    # Organization CRUD
    create_organization,
    get_organization,
    get_organizations,
    update_organization,
    delete_organization,
    # Project CRUD
    create_project,
    get_project,
    get_project_by_slug,
    get_projects,
    update_project,
    delete_project,
    # Project Members
    add_project_member,
    get_project_members,
    update_project_member_role,
    remove_project_member,
    # Requirement CRUD
    create_requirement,
    get_requirement,
    update_requirement,
    delete_requirement,
    list_requirements,
    get_requirement_children,
    get_requirement_history,
    transition_requirement_status,
    update_requirement_priority,
    # User CRUD
    get_user_by_id,
    get_user_by_email,
    search_users,
)
from .schemas import (
    # Requirement schemas
    RequirementCreate,
    RequirementUpdate,
    RequirementResponse,
    RequirementListItem,
    RequirementListResponse,
    RequirementHistoryResponse,
    StatusTransition,
    PriorityUpdate,
    # Organization schemas
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    OrganizationListResponse,
    # Project schemas
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectListResponse,
    # Project Member schemas
    ProjectMemberCreate,
    ProjectMemberUpdate,
    ProjectMemberResponse,
    # User schemas
    UserResponse,
    UserListResponse,
)

__all__ = [
    # Version
    "__version__",
    # Models
    "Base",
    "User",
    "Organization",
    "OrganizationMember",
    "Project",
    "ProjectMember",
    "Requirement",
    "RequirementHistory",
    "PersonalAccessToken",
    "RequirementType",
    "LifecycleStatus",
    "ProjectStatus",
    "ProjectVisibility",
    "ProjectRole",
    "MemberRole",
    # CRUD functions
    "create_organization",
    "get_organization",
    "get_organizations",
    "update_organization",
    "delete_organization",
    "create_project",
    "get_project",
    "get_project_by_slug",
    "get_projects",
    "update_project",
    "delete_project",
    "add_project_member",
    "get_project_members",
    "update_project_member_role",
    "remove_project_member",
    "create_requirement",
    "get_requirement",
    "update_requirement",
    "delete_requirement",
    "list_requirements",
    "get_requirement_children",
    "get_requirement_history",
    "transition_requirement_status",
    "update_requirement_priority",
    "get_user_by_id",
    "get_user_by_email",
    "search_users",
    # Schemas
    "RequirementCreate",
    "RequirementUpdate",
    "RequirementResponse",
    "RequirementListItem",
    "RequirementListResponse",
    "RequirementHistoryResponse",
    "StatusTransition",
    "PriorityUpdate",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationListResponse",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "ProjectMemberCreate",
    "ProjectMemberUpdate",
    "ProjectMemberResponse",
    "UserResponse",
    "UserListResponse",
]
